version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "7001:7001"
    volumes:
      - /root/serviceAccountKey.json /workdir/serviceAccountKey.json


  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DATABASE: ticket_merchant
    ports:
      - "5432:5432"
    volumes: 
      - ./ticket_merchant.sql:/docker-entrypoint-initdb.d/ticket_merchant.sql
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh

